### ISSUE TITLE
Warning: missed something in sprint planning

### ISSUE THREAD

**Issue by gsczechowski** [bradwarrum/CS307-Server#10]
The server and client need to do: 
As a user I would like to be able to create an item entry for a product that
does not have an associated UPC code. (Backlog #5)

Only created work time for the android app. Server will need API adaption to cooperate.

**Comment by bradwarrum** [comment]
@gsczechowski 
I accidentally added the functionality to a table lower in the list.  Server-side additions were accounted for in the planning document.
