### ISSUE TITLE
Link vs Create UPC

### ISSUE THREAD

**Issue by gsczechowski** [bradwarrum/CS307-Server#16]
Does creating a UPC link?

also what is the format of units int (enumeration) or string:
{
    "description" : "Planter's Cocktail Peanuts",
    "packageName" : 23,
    "packageUnits" : 3,
    "packageSize" : 12.0
}

{
    "description" : "Orange",
    "packageName" : "each",
    "packageUnits" : "unit",
    "packageSize" : 1.0
}

**Comment by bradwarrum** [comment]
This was a documentation error.  Units is enumerated.  PackageName is not.
