### ISSUE TITLE
UserRegistrationWrapper increments UserId on insertion fail

### ISSUE THREAD

**Issue by bradwarrum** [bradwarrum/CS307-Server#2]
#1 changed the UserRegistrationWrapper to use 1 query instead of 2 and simply use the SQLState to detect presence of a user with a specific email.  On insertion the auto-increment field increments even if there is an exception, so userIDs are not contiguous.

Is this easily fixable by modifying the SQL query within the registration wrapper?

/cc @rogerse

**Comment by rogerse** [comment]
This is a normal behavior and shouldn't cause any issues. if we wanted to later we could create a script that would update the User Ids.
