### ISSUE TITLE
Setting list quantity to 0 does not remove item.

### ISSUE THREAD

**Issue by gsczechowski** [bradwarrum/CS307-Server#20]
sent:
    {
    "items": [
    {
    "UPC": "011110799906",
    "fractional": 1,
    "quantity": 0
    }
    ],
    "version": 1428634713911
    }

got back:

listJSON:
    {
    "items": [
    {
    "UPC": "011110799906",
    "description": "ibu",
    "packaging": {
    "packageName": "bottle",
    "unitAbbreviation": "units",
    "unitName": "units",
    "packageSize": 500.0,
    "unitID": 14
    },
    "fractional": 1,
    "quantity": 0
    },
    {
    "UPC": "00001",
    "description": "banana",
    "packaging": {
    "packageName": "bunch",
    "unitAbbreviation": "units",
    "unitName": "units",
    "packageSize": 1.0,
    "unitID": 14
    },
    "fractional": 1,
    "quantity": 0
    },
    {
    "UPC": "00002",
    "description": "oranges",
    "packaging": {
    "packageName": "orange",
    "unitAbbreviation": "units",
    "unitName": "units",
    "packageSize": 1.0,
    "unitID": 14
    },
    "fractional": 3,
    "quantity": 0
    },
    {
    "UPC": "00006",
    "description": "pears",
    "packaging": {
    "packageName": "pear",
    "unitAbbreviation": "units",
    "unitName": "units",
    "packageSize": 1.0,
    "unitID": 14
    },
    "fractional": 0,
    "quantity": 5
    }
    ],
    "name": "list1",
    "version": 1428634838270
    }

**Comment by bradwarrum** [comment]
Quantity and fractional must both be 0 to remove the item from the list. Quantity = 0, fractional = 1 is a valid net quantity (0.01 packages)

**Comment by gsczechowski** [comment]
is fractional a percentage?

**Comment by bradwarrum** [comment]
Yes, it equals 1/100th of a full unit

**Comment by gsczechowski** [comment]
Well that clarifies a lot... I thought it was quantity/fractional

**Comment by gsczechowski** [comment]
Well that means some UI needs a lot a lot. Oh well not for this sprint.

Next spring I need like a 10hr make the UI pretty and more functional objective....
