### ISSUE TITLE
When creating custom UPC check to see if item with same name exists.

### ISSUE THREAD

**Issue by gsczechowski** [bradwarrum/CS307-Server#21]
If there is already something called apples return that as the UPC to guard against duplicates.

**Comment by bradwarrum** [comment]
Is there any way to implement this client side? I think it would be difficult to guard against situations where its spelled slightly differently, capitalized, etc.  I don't know how the android layout works, but is there a way to show similar names just before they confirm they want to generate a new UPC? That way the user can review the similarities manually before the request is sent.

This could be implemented server side, but it would be fairly involved so it will be a sprint 3 thing if anything.

**Comment by bradwarrum** [comment]
Now returns error code 18 if there is a duplicate
https://github.com/bradwarrum/CS307-Server/blob/02897e5d1c4fe1f0680fcf80c1699cd425edb93c/api/APIErrorCodes.md
