### ISSUE TITLE
Link failing

### ISSUE THREAD

**Issue by gsczechowski** [bradwarrum/CS307-Server#7]
03-06 12:58:31.537  22023-22328/com.example.android.virtualpantry V/linkItem﹕ regstr={
    "description": "coke zero",
    "unitName": "bottle"
    }
03-06 12:58:31.607  22023-22328/com.example.android.virtualpantry E/linkItem﹕ Unkwnon
    java.io.FileNotFoundException: http://IP_REDACTED/households/3/items/049000045840/link?token=5uhdVgttv6nMmxNjwAew1jOGtGphi3yh

Attempting to link an item resulting in 400 malformed input

**Comment by gsczechowski** [comment]
unitName field cannot exceed 4 chars

**Comment by bradwarrum** [comment]
This has been modified to 20 chars in a recent update for testing purposes, but will be modified again in the near future to an enumeration method
